### PR TITLE
Section descriptions

### PR DESCRIPTION
**Pull request by knmeynell**
Added initial content.

### CODE REVIEW

**Review by nicorusti — COMMENTED** [review]
This is a first skeleton, it needs a tiny bit more text to better explain what we want to achieve with the discussion. 
We might submit it now, but we'll have to update it with a bit more content soonish

**Review by knmeynell — COMMENTED** [review]
Okay

**Comment by knmeynell** [comment]
The outline looks fairly complete now. We can start filling in the details from this.

**Review by knmeynell — COMMENTED** [review]
Okay

**Review by nicorusti — APPROVED** [review]

**Pull request merged**
